local lib = LibStub("LibInstances")
lib:addGroup(1, "Classic Dungeons")
lib:addGroup(2, "Burning Crusade Normal")
lib:addGroup(3, "Burning Crusade Heroic")
lib:addGroup(4, "Wrath of the Lich King Normal")
lib:addGroup(5, "Wrath of the Lich King Heroic")
lib:addGroup(6, "Classic Raid")
lib:addGroup(7, "Burning Crusade Raid")
lib:addGroup(8, "Wrath of the Lich King Raid (10)")
lib:addGroup(9, "Wrath of the Lich King Raid (25)")
lib:addGroup(11, "World Events")
lib:addGroup(12, "Cataclysm Heroic")
lib:addGroup(13, "Cataclysm Normal")
lib:addGroup(14, "Cataclysm Raid (25)")
lib:addGroup(15, "Cataclysm Raid (10)")
lib:addGroup(20, "Rated Battleground")
lib:addGroup(33, "Hour of Twilight Heroic")
lib:addGroup(174, "Titan Rune Dungeon Protocol Gamma")
lib:addGroup(175, "Titan Rune Dungeon Protocol Beta")
lib:addGroup(176, "Titan Rune Dungeon Protocol Alpha")